# Generated by Django 5.2.4 on 2025-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
